Create Table: CREATE TABLE `morphmarket` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `status` enum('Enable','Disable','Unset') DEFAULT 'Disable',
  `mm_id` varchar(32) DEFAULT NULL,
  `images_html` text DEFAULT NULL,
  `images` text DEFAULT NULL,
  `snake_title` varchar(255) DEFAULT NULL,
  `snake_internal_id` varchar(32) DEFAULT NULL,
  `snake_price` varchar(32) DEFAULT NULL,
  `snake_url` varchar(255) DEFAULT NULL,
  `quantity` varchar(12) DEFAULT NULL,
  `a_id` varchar(32) DEFAULT NULL,
  `traits` text DEFAULT NULL,
  `sex` varchar(32) DEFAULT NULL,
  `maturity` varchar(32) DEFAULT NULL,
  `proven_breeder` varchar(32) DEFAULT NULL,
  `price` varchar(32) DEFAULT NULL,
  `dob_MM` varchar(32) DEFAULT NULL,
  `dob_DD` varchar(32) DEFAULT NULL,
  `dob_YY` varchar(32) DEFAULT NULL,
  `diet_prey_state` varchar(32) DEFAULT NULL,
  `diet_prey_food` varchar(32) DEFAULT NULL,
  `clutch_number` varchar(32) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `negotiation` varchar(32) DEFAULT NULL,
  `trades` varchar(32) DEFAULT NULL,
  `availability` varchar(32) DEFAULT NULL,
  `analytics_html` text DEFAULT NULL,
  `impressions` varchar(32) DEFAULT NULL,
  `clicks` varchar(32) DEFAULT NULL,
  `inquiries` varchar(32) DEFAULT NULL,
  `tag` varchar(255) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=148 DEFAULT CHARSET=latin1

